### ISSUE TITLE
Signature salah

### ISSUE THREAD

**Issue by bionyxxx** [svakode/svaflazz#2]
Halo, saya mengalami kendala dimana ketika menggunakan dev api key proses topup trx berjalan sesuai namun ketika dicoba menggunakan production key.. respon pada proses transaksi selalu **Signature Salah** namun untuk proses get price list aman tidak ada masalah walaupun menggunakan producion key

> {"error":{"summary":"Got error with message: `Signature Anda salah` and response code: `41`","message":"Signature Anda salah","response_code":"41"}}

**Comment by irfanhfzh** [comment]
@bionyxxx apakah ada solusinya? saya ada masalah yang sama dengan anda
